# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(500, 122)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 93, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 93, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 93, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 93, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 93, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 93, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 93, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 93, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 93, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Widget.setPalette(palette)
        Widget.setStyleSheet("QWidget {\n"
"    background-color: #765D69;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #F1828D;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FCD08A;\n"
"    color: white\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: none;\n"
"    background-color: #F1828D;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #F1828D;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.weight_line = QtWidgets.QLineEdit(Widget)
        self.weight_line.setGeometry(QtCore.QRect(90, 70, 81, 21))
        self.weight_line.setObjectName("weight_line")
        self.is_available_combo = QtWidgets.QComboBox(Widget)
        self.is_available_combo.setGeometry(QtCore.QRect(270, 40, 111, 22))
        self.is_available_combo.setObjectName("is_available_combo")
        self.is_free_label = QtWidgets.QLabel(Widget)
        self.is_free_label.setGeometry(QtCore.QRect(200, 40, 61, 20))
        self.is_free_label.setObjectName("is_free_label")
        self.id_title_label = QtWidgets.QLabel(Widget)
        self.id_title_label.setGeometry(QtCore.QRect(26, 10, 47, 13))
        self.id_title_label.setObjectName("id_title_label")
        self.ok_btn = QtWidgets.QPushButton(Widget)
        self.ok_btn.setGeometry(QtCore.QRect(400, 40, 81, 51))
        self.ok_btn.setObjectName("ok_btn")
        self.abount_label = QtWidgets.QLabel(Widget)
        self.abount_label.setGeometry(QtCore.QRect(26, 60, 31, 41))
        self.abount_label.setObjectName("abount_label")
        self.id_label = QtWidgets.QLabel(Widget)
        self.id_label.setGeometry(QtCore.QRect(90, 10, 31, 16))
        self.id_label.setObjectName("id_label")
        self.price_label = QtWidgets.QLabel(Widget)
        self.price_label.setGeometry(QtCore.QRect(200, 70, 31, 20))
        self.price_label.setObjectName("price_label")
        self.price_line = QtWidgets.QLineEdit(Widget)
        self.price_line.setGeometry(QtCore.QRect(270, 70, 111, 21))
        self.price_line.setObjectName("price_line")
        self.name_label = QtWidgets.QLabel(Widget)
        self.name_label.setGeometry(QtCore.QRect(26, 40, 47, 13))
        self.name_label.setObjectName("name_label")
        self.name_line = QtWidgets.QLineEdit(Widget)
        self.name_line.setGeometry(QtCore.QRect(90, 40, 81, 21))
        self.name_line.setObjectName("name_line")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.is_free_label.setText(_translate("Widget", "Is Available"))
        self.id_title_label.setText(_translate("Widget", "Id"))
        self.ok_btn.setText(_translate("Widget", "OK"))
        self.abount_label.setText(_translate("Widget", "Weight"))
        self.id_label.setText(_translate("Widget", "NONE"))
        self.price_label.setText(_translate("Widget", "Price"))
        self.name_label.setText(_translate("Widget", "Name"))
